name: flutter_lap
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4  # Ensure you have the correct version
  path: ^1.8.0   
  provider: ^6.1.2 # For state management
  shared_preferences: ^2.1.1 # For local storage
  flutter_local_notifications: ^12.0.4 # For reminders     # For handling file paths
  uuid: ^3.0.7
  fl_chart: ^0.69.2  # For charts
  cupertino_icons: ^1.0.8
  intl: ^0.18.0      # For internationalization (date formatting, etc.)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dice-1.png
    - assets/images/dice-2.png
    - assets/images/dice-3.png
    - assets/images/dice-4.png
    - assets/images/dice-5.png
    - assets/images/dice-6.png
    - assets/images/dart.png
    - assets/images/firebase.png
    - assets/images/flutter.png
    - assets/w4-s2/bird.jpg
    - assets/w4-s2/bird2.jpg
    - assets/w4-s2/girl.jpg
    - assets/w4-s2/insect.jpg
    - assets/w4-s2/man.jpg
    - assets/w6-s2/quiz-logo.png
